### ISSUE TITLE
where is the code? 

### ISSUE THREAD

**Issue by aktiger** [feichtenhofer/Detect-Track#1]

**Comment by Peratham** [comment]
Please see the author's ReadMe.MD.

> This repository will **soon** contain the code for our ICCV 2017 paper:

**Comment by pribadihcr** [comment]
+1

**Comment by yl1991** [comment]
+1

**Comment by ElPatou** [comment]
Did you already decide on a release date?

**Comment by AndrewZhao** [comment]
+1

**Comment by jaye16** [comment]
+1

**Comment by tshizys** [comment]
+1

**Comment by karolmajek** [comment]
Please stop writing +1 comments, just click :+1: 
Everyone who is watching this gets a notification :bell: 
Thanks!
