### ISSUE TITLE
Where is meta_vid.mat?

### ISSUE THREAD

**Issue by jiaozizhao** [feichtenhofer/Detect-Track#10]
In the imdb funcition, there is ´      meta_det             = load(fullfile(devkit_path, 'data', 'meta_vid.mat')); ´, where can I find the ´meta_vid.mat´? Thanks.

**Comment by feichtenhofer** [comment]
You need to download the ILSVRC detection kit.

**Comment by wangshy31** [comment]
I also encountered this problem, could you provide this meta_vid.mat?

**Comment by Jankyee** [comment]
so, where did you download?
