### ISSUE TITLE
Evaluation devkit: Errors during evaluation

### ISSUE THREAD

**Issue by Feynman27** [feichtenhofer/Detect-Track#11]
@feichtenhofer Great work! Thanks for sharing. I'm attempting to run inference on a single VID video snippet and am running into errors when trying to call functions within the original Imagenet devkit ( taken from [here](http://image-net.org/challenges/LSVRC/2015/download-images-3j16.php)). Are you using a custom/modified devkit?

The first error is an IO error from `devkit/evaluation/eval_vid_detection` on l117. I noticed the number of columns had changed in the input file `predict_file`, and I could fix this by changing:

```bash
[img_ids obj_labels obj_confs xmin ymin xmax ymax] = ...
        textread(predict_file,'%d %d %f %f %f %f %f');
```
to 
```bash
[img_ids obj_labels unk obj_confs xmin ymin xmax ymax] = ...
        textread(predict_file,'%d %d %d %f %f %f %f %f');
```

After modifying the line above, I ran into another error in the evaluation:

```bash
Undefined function or variable 'eval_vid_tracking'.
```
This function is called within `imdb/imdb_eval_ilsvrc14.m` [here](https://github.com/feichtenhofer/Detect-Track/blob/master/imdb/imdb_eval_ilsvrc14.m#L131). I noticed the file `eval_vid_tracking.m` doesn't exist and it doesn't seem to be in this repo. If you are using a modified devkit, can you please push it?

**Comment by huangcong77** [comment]
@Feynman27 Hi, did you compile caffe-rfcn as readme successfully?

**Comment by Feynman27** [comment]
Yes.

**Comment by feichtenhofer** [comment]
@Feynman27 thanks! Please use the ILSVRC2016 devkit or comment the function call. The ILSVRC2015 you are using does not support tracking evaluation.

**Comment by samanthawyf** [comment]
Hi, @Feynman27 @feichtenhofer  @huangcong77 , I met the same problem. However, I tried many times but still could not open the ILSVRC2016 website. Can you share the ILSVRC2016 devkit, my email address is 3130102352@zju.edu.cn. Thanks a lot!

**Comment by kodukulav** [comment]
wget http://image-net.org/image/ILSVRC2016/ILSVRC2016_devkit.tar.gz worked for me
