### ISSUE TITLE
It'd be nice to have a demo video

### ISSUE THREAD

**Issue by agirbau** [feichtenhofer/Detect-Track#13]
Hi!
I think the title is self-explanatory. If you could add some demo to run it directly after compiling it would be very nice to have.
Nice work so far!

**Comment by fanyix** [comment]
Agree with @agirbau, it would be great if there is a test-only demo code that could reproduce the 79.8% mAP reported in the paper.

**Comment by feichtenhofer** [comment]
Please read the README. If you run the TESTING blocks in script_DetectTrack_ILSVRC_vid_ResNet_OHEM_rpn.m it will reproduce the 81% mAP.
