### ISSUE TITLE
which train prototxt did you use?

### ISSUE THREAD

**Issue by Jankyee** [feichtenhofer/Detect-Track#14]
There are so many train prototxts in the 'models/rfcn_prototxts/ResNet-101L_ILSVRCvid_corr' directory, what is the difference and which one did you use? Thanks!
![screenshot from 2018-01-23 16 51 03](https://user-images.githubusercontent.com/21698398/35266261-a868ac14-005d-11e8-8162-d19866c1d40f.png)

**Comment by feichtenhofer** [comment]
Please see the first line of the solver file:
net: "./models/rfcn_prototxts/ResNet-101L_ILSVRCvid_corr/train_val_track.prototxt"
