### ISSUE TITLE
Could you provide example testing command?

### ISSUE THREAD

**Issue by JunweiLiang** [feichtenhofer/Detect-Track#16]
Could you provide an example command to get the results on VID validation set? How to reproduce the 79.8 mAP as in the paper using rfcn_test_vid()? I'm not sure what the inputs: conf, imdb, roidb, etc., correspond to. Thank you!

**Comment by feichtenhofer** [comment]
Please read the README. If you run the TESTING blocks in script_DetectTrack_ILSVRC_vid_ResNet_OHEM_rpn.m it will reproduce the 81% mAP.
