### ISSUE TITLE
How to implement RoI Tracking?

### ISSUE THREAD

**Issue by go2star** [feichtenhofer/Detect-Track#5]
In the track-regression, RoI pooling is operated on the concatenation of the bounding box regression features and the correlation feature. I want to know the details about RoI pooling such as which frame's roi should be used.

**Comment by jugalsheth92** [comment]
According to my understanding, During **inference**, all Roi's from frame _T_ should be used to regress their locations in frame _T+t_ . And during **training** Roi's that have object correspondence in frame _T_ and frame _T+t_ should be used.
